### ISSUE TITLE
加载了百度或高德在线底图，然后再用该插件加载一个自定义的矢量切片服务，图层永远在底图下面被挡住

### ISSUE THREAD

**Issue by PurityChan** [maptalks/maptalks.mapboxgl#14]
![image](https://user-images.githubusercontent.com/8343216/76498547-0e7abf80-6478-11ea-8e06-8d8bf9869fa9.png)

原生maptalk能够直接加载矢量切片嘛？有没有其他方式

**Comment by fuzhenn** [comment]
可以在mapboxgl图层的options里设置container: 'front'，把它设置到前面。

maptalks的矢量瓦片插件正在开发，过段时间就会发布。
