### ISSUE TITLE
npm install maptalks.mapboxgl. 出错！

### ISSUE THREAD

**Issue by theseusyang** [maptalks/maptalks.mapboxgl#18]
执行
npm install maptalks.mapboxgl.
出错

npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/maptalks.mapboxgl. - Not found
npm ERR! 404 
npm ERR! 404  'maptalks.mapboxgl.@latest' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

**Comment by fuzhenn** [comment]
你的命令最后多了一个`.`，应该是
```shell
npm install maptalks.mapboxgl
```
