### ISSUE TITLE
Zooming glitches on Hi DPI displays

### ISSUE THREAD

**Issue by sibbl** [maptalks/maptalks.mapboxgl#3]
Zooming does not work properly on devices with DPI > 100%. It zooms in at the position where I scroll or pinch with 2 fingers, but after finishing the zoom interaction, the map snaps to another point. As this points is mostly about half the distance from the top and left, I guess that some mouse/finger coordinates are not multiplied with `window.devicePixelRatio` somewhere.

**Comment by fuzhenn** [comment]
Thanks for issue!
I will find some time to fix it.

**Comment by kidlu1412** [comment]
I have found this bug, @fuzhenn @sibbl ,function drawOnInteracting(), I think zoomTo is not nessecery, only use syncMap, It will fit this problem
_class.prototype.drawOnInteracting = function drawOnInteracting(e) {


        var map = this.getMap();
        if (!this.glmap || !map) {
            return;
        }
        this._syncMap();
       /* if (map.isZooming() && e.origin) {
            var origin = e['origin'];
            origin = map.containerPointToCoordinate(origin);
            origin = new mapboxgl.LngLat(origin.x, origin.y);
            var cameraOptions = {
                'around': origin,
                'duration': 0
            };
            // use zoomTo instead of jumpTo, becos we need to set around to zoom around zoom origin point.
            this.glmap.zoomTo(map.getZoom() - 1, cameraOptions);
        } else {
            this._syncMap();
        }*/
    };

**Comment by fuzhenn** [comment]
Great! Thanks! @kidlu1412 
Do you mind proposing a pull request?

**Comment by fuzhenn** [comment]
Fixed and published as v0.3.1
Sorry for my late reply
