### ISSUE TITLE
ES6 Import

### ISSUE THREAD

**Issue by jakob-fuchs** [maptalks/maptalks.mapboxgl#7]
I'm trying to import the MapboxGL plugin the following way:

```javascript
  import * as MapTalks from 'maptalks/dist/maptalks';
  import 'maptalks/dist/maptalks.css';
  import { MapboxglLayer } from 'maptalks.mapboxgl';
```

Getting the following error message:

`./node_modules/maptalks.mapboxgl/dist/maptalks.mapboxgl.es.js
Module not found: Error: Can't resolve 'mapboxgl' in '/home/xxx/xxx/xxx/app/node_modules/maptalks.mapboxgl/dist'`

Any ideas why that is not working?

**Comment by jakob-fuchs** [comment]
It seems like the MapboxGL package is called `mapbox-gl` not. Updating the import here seems fix the problem: https://github.com/maptalks/maptalks.mapboxgl/blob/f207a4576eb94bcd5091a70574d929fb82ef9044/dist/maptalks.mapboxgl.es.js#L10

**Comment by davidweining2333** [comment]
@jakob-fuchs 

> Failed to compile.
> 
> ./node_modules/_maptalks.mapboxgl@0.3.3@maptalks.mapboxgl/dist/maptalks.mapboxgl.es.js
> Module not found: Can't resolve 'mapbox-gl' in 'D:\w-code\neweconomy\nc\node_modules\_maptalks.mapbo
> xgl@0.3.3@maptalks.mapboxgl\dist'

did your resolved this ? i have this error when i  

> import {MapboxglLayer} from "maptalks.mapboxgl";
